"""Edge host user-data generator — builds cloud-init/user-data for agent and appliance modes."""

from __future__ import annotations

import logging
from typing import Any

from ..defaults import load_defaults

logger = logging.getLogger(__name__)


def generate_agent_userdata(
    token: str,
    palette_endpoint: str,
    project_uid: str,
    edge_id: str = "",
    site_name: str = "edge-site",
    tags: dict[str, str] | None = None,
    proxy: dict[str, str] | None = None,
    fips: bool = False,
) -> str:
    """Generate bash user-data for agent mode edge hosts.

    Follows the official pattern:
    1. Install prerequisites (conntrack, jq, etc.)
    2. Write cloud-config YAML to /tmp/userdata
    3. Set USERDATA env var
    4. Download and run palette-agent-install.sh
    """

    defaults = load_defaults("edge-native")
    agent_defaults = defaults.get("agent", {})

    if fips:
        script_url = agent_defaults.get(
            "install_script_url_fips",
            "https://github.com/spectrocloud/agent-mode/releases/latest/download/palette-agent-install-fips.sh",
        )
    else:
        script_url = agent_defaults.get(
            "install_script_url",
            "https://github.com/spectrocloud/agent-mode/releases/latest/download/palette-agent-install.sh",
        )

    # Strip https:// from palette endpoint for the config
    endpoint = palette_endpoint.replace("https://", "").replace("http://", "")

    # Build tags YAML
    tags_yaml = ""
    if tags:
        tag_lines = "\n".join(f"      {k}: {v}" for k, v in tags.items())
        tags_yaml = f"    tags:\n{tag_lines}"

    # Build the cloud-config YAML content
    cloud_config = [
        "#cloud-config",
        "install:",
        "  reboot: true",
        "  poweroff: false",
        "",
        "stylus:",
        "  vip:",
        "    skip: true",
        "  site:",
        f"    name: {site_name}",
    ]

    if tags_yaml:
        cloud_config.append(tags_yaml)

    cloud_config.extend([
        f"    edgeHostToken: {token}",
        f"    paletteEndpoint: {endpoint}",
    ])

    if project_uid:
        cloud_config.append(f"    projectUid: {project_uid}")

    if edge_id:
        cloud_config.append(f"    edgeHostUid: {edge_id}")

    # Kairos user setup
    cloud_config.extend([
        "stages:",
        "  initramfs:",
        "    - users:",
        "        kairos:",
        "          groups:",
        "            - sudo",
        "          passwd: kairos",
    ])

    cloud_config_str = "\n".join(cloud_config)

    # Build the bash script
    lines = [
        "#!/bin/bash",
        "set -ex",
        "",
        "# Palette Edge Agent Installation",
        "# Generated by Palette Agentic",
        "",
        "# Install prerequisites",
        "apt-get update",
        "apt-get install -y conntrack jq zstd rsync curl wget systemd-timesyncd",
        "echo '1' > /proc/sys/net/ipv4/ip_forward",
        "",
    ]

    # Proxy settings
    if proxy:
        if proxy.get("http_proxy"):
            lines.append(f'export HTTP_PROXY="{proxy["http_proxy"]}"')
            lines.append(f'export http_proxy="{proxy["http_proxy"]}"')
        if proxy.get("https_proxy"):
            lines.append(f'export HTTPS_PROXY="{proxy["https_proxy"]}"')
            lines.append(f'export https_proxy="{proxy["https_proxy"]}"')
        if proxy.get("no_proxy"):
            lines.append(f'export NO_PROXY="{proxy["no_proxy"]}"')
            lines.append(f'export no_proxy="{proxy["no_proxy"]}"')
        lines.append("")

    # Write cloud-config to file
    lines.append("# Write cloud-config userdata")
    lines.append(f"cat << 'EOF' > /tmp/userdata")
    lines.append(cloud_config_str)
    lines.append("EOF")
    lines.append("")

    # Run the installer
    lines.extend([
        "# Download and run the agent installer",
        "export USERDATA=/tmp/userdata",
        f'curl -Ls "{script_url}" | bash',
    ])

    return "\n".join(lines)


def generate_appliance_userdata(
    token: str,
    palette_endpoint: str,
    project_uid: str,
    edge_id: str = "",
    site_name: str = "edge-site",
    tags: dict[str, str] | None = None,
    proxy: dict[str, str] | None = None,
) -> str:
    """Generate user-data YAML for appliance mode edge hosts (Kairos-based).
    Appliance mode uses cloud-config YAML directly as user-data."""

    endpoint = palette_endpoint.replace("https://", "").replace("http://", "")

    lines = [
        "#cloud-config",
        "install:",
        "  reboot: true",
        "  poweroff: false",
        "",
        "stylus:",
        "  vip:",
        "    skip: true",
        "  site:",
        f"    name: {site_name}",
    ]

    if tags:
        lines.append("    tags:")
        for k, v in tags.items():
            lines.append(f"      {k}: {v}")

    lines.extend([
        f"    edgeHostToken: {token}",
        f"    paletteEndpoint: {endpoint}",
    ])

    if project_uid:
        lines.append(f"    projectUid: {project_uid}")

    if edge_id:
        lines.append(f"    edgeHostUid: {edge_id}")

    if proxy:
        lines.append("  network:")
        if proxy.get("http_proxy"):
            lines.append(f"    httpProxy: {proxy['http_proxy']}")
        if proxy.get("https_proxy"):
            lines.append(f"    httpsProxy: {proxy['https_proxy']}")
        if proxy.get("no_proxy"):
            lines.append(f"    noProxy: {proxy['no_proxy']}")

    # Kairos user setup
    lines.extend([
        "stages:",
        "  initramfs:",
        "    - users:",
        "        kairos:",
        "          groups:",
        "            - sudo",
        "          passwd: kairos",
    ])

    return "\n".join(lines)
