# References:
# - https://golangci-lint.run/usage/linters/

run:
  timeout: 10m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # too strict
      - shadow # too strict

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - ineffassign
        - staticcheck
        - unused
        - revive