# References:
# - https://golangci-lint.run/usage/linters/

version: "2"

run:
  timeout: 10m

issues:
  exclude-use-default: false
  exclude-dirs:
    - "api/apiutil"
    - "api/client/version1"
  exclude-files:
    - ".*_test\\.go"

formatters:
  enable:
    - goimports

linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - revive
