# References:
# - https://golangci-lint.run/usage/linters/

run:
  allow-parallel-runners: true
  timeout: 10m

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude-dirs:
    - "api/apiutil"
    - "api/client/v1"
  exclude-files:
    - ".*_test\\.go"

linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - goconst
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - revive
