// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-api-go/models"
)

// NewV1BasicOciRegistriesValidateParams creates a new V1BasicOciRegistriesValidateParams object
// with the default values initialized.
func NewV1BasicOciRegistriesValidateParams() *V1BasicOciRegistriesValidateParams {
	var ()
	return &V1BasicOciRegistriesValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1BasicOciRegistriesValidateParamsWithTimeout creates a new V1BasicOciRegistriesValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1BasicOciRegistriesValidateParamsWithTimeout(timeout time.Duration) *V1BasicOciRegistriesValidateParams {
	var ()
	return &V1BasicOciRegistriesValidateParams{

		timeout: timeout,
	}
}

// NewV1BasicOciRegistriesValidateParamsWithContext creates a new V1BasicOciRegistriesValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1BasicOciRegistriesValidateParamsWithContext(ctx context.Context) *V1BasicOciRegistriesValidateParams {
	var ()
	return &V1BasicOciRegistriesValidateParams{

		Context: ctx,
	}
}

// NewV1BasicOciRegistriesValidateParamsWithHTTPClient creates a new V1BasicOciRegistriesValidateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1BasicOciRegistriesValidateParamsWithHTTPClient(client *http.Client) *V1BasicOciRegistriesValidateParams {
	var ()
	return &V1BasicOciRegistriesValidateParams{
		HTTPClient: client,
	}
}

/*V1BasicOciRegistriesValidateParams contains all the parameters to send to the API endpoint
for the v1 basic oci registries validate operation typically these are written to a http.Request
*/
type V1BasicOciRegistriesValidateParams struct {

	/*Body*/
	Body *models.V1BasicOciRegistrySpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) WithTimeout(timeout time.Duration) *V1BasicOciRegistriesValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) WithContext(ctx context.Context) *V1BasicOciRegistriesValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) WithHTTPClient(client *http.Client) *V1BasicOciRegistriesValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) WithBody(body *models.V1BasicOciRegistrySpec) *V1BasicOciRegistriesValidateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 basic oci registries validate params
func (o *V1BasicOciRegistriesValidateParams) SetBody(body *models.V1BasicOciRegistrySpec) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1BasicOciRegistriesValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
