// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// V1AuthMfaDevicesListReader is a Reader for the V1AuthMfaDevicesList structure.
type V1AuthMfaDevicesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AuthMfaDevicesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AuthMfaDevicesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1AuthMfaDevicesListOK creates a V1AuthMfaDevicesListOK with default headers values
func NewV1AuthMfaDevicesListOK() *V1AuthMfaDevicesListOK {
	return &V1AuthMfaDevicesListOK{}
}

/*
V1AuthMfaDevicesListOK handles this case with default header values.

(empty)
*/
type V1AuthMfaDevicesListOK struct {
	Payload models.V1MfaDevices
}

func (o *V1AuthMfaDevicesListOK) Error() string {
	return fmt.Sprintf("[GET /v1/auth/mfa/devices][%d] v1AuthMfaDevicesListOK  %+v", 200, o.Payload)
}

func (o *V1AuthMfaDevicesListOK) GetPayload() models.V1MfaDevices {
	return o.Payload
}

func (o *V1AuthMfaDevicesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
