// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1ClusterProfilesPacksRefUpdateReader is a Reader for the V1ClusterProfilesPacksRefUpdate structure.
type V1ClusterProfilesPacksRefUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1ClusterProfilesPacksRefUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1ClusterProfilesPacksRefUpdateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1ClusterProfilesPacksRefUpdateNoContent creates a V1ClusterProfilesPacksRefUpdateNoContent with default headers values
func NewV1ClusterProfilesPacksRefUpdateNoContent() *V1ClusterProfilesPacksRefUpdateNoContent {
	return &V1ClusterProfilesPacksRefUpdateNoContent{}
}

/*
V1ClusterProfilesPacksRefUpdateNoContent handles this case with default header values.

The resource was updated successfully
*/
type V1ClusterProfilesPacksRefUpdateNoContent struct {
}

func (o *V1ClusterProfilesPacksRefUpdateNoContent) Error() string {
	return fmt.Sprintf("[PATCH /v1/clusterprofiles/{uid}/packRefs][%d] v1ClusterProfilesPacksRefUpdateNoContent ", 204)
}

func (o *V1ClusterProfilesPacksRefUpdateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
