// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1CloudAccountsCloudStackDeleteParams creates a new V1CloudAccountsCloudStackDeleteParams object
// with the default values initialized.
func NewV1CloudAccountsCloudStackDeleteParams() *V1CloudAccountsCloudStackDeleteParams {
	var ()
	return &V1CloudAccountsCloudStackDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1CloudAccountsCloudStackDeleteParamsWithTimeout creates a new V1CloudAccountsCloudStackDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1CloudAccountsCloudStackDeleteParamsWithTimeout(timeout time.Duration) *V1CloudAccountsCloudStackDeleteParams {
	var ()
	return &V1CloudAccountsCloudStackDeleteParams{

		timeout: timeout,
	}
}

// NewV1CloudAccountsCloudStackDeleteParamsWithContext creates a new V1CloudAccountsCloudStackDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1CloudAccountsCloudStackDeleteParamsWithContext(ctx context.Context) *V1CloudAccountsCloudStackDeleteParams {
	var ()
	return &V1CloudAccountsCloudStackDeleteParams{

		Context: ctx,
	}
}

// NewV1CloudAccountsCloudStackDeleteParamsWithHTTPClient creates a new V1CloudAccountsCloudStackDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1CloudAccountsCloudStackDeleteParamsWithHTTPClient(client *http.Client) *V1CloudAccountsCloudStackDeleteParams {
	var ()
	return &V1CloudAccountsCloudStackDeleteParams{
		HTTPClient: client,
	}
}

/*
V1CloudAccountsCloudStackDeleteParams contains all the parameters to send to the API endpoint
for the v1 cloud accounts cloud stack delete operation typically these are written to a http.Request
*/
type V1CloudAccountsCloudStackDeleteParams struct {

	/*UID
	  CloudStack cloud account uid

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) WithTimeout(timeout time.Duration) *V1CloudAccountsCloudStackDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) WithContext(ctx context.Context) *V1CloudAccountsCloudStackDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) WithHTTPClient(client *http.Client) *V1CloudAccountsCloudStackDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) WithUID(uid string) *V1CloudAccountsCloudStackDeleteParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the v1 cloud accounts cloud stack delete params
func (o *V1CloudAccountsCloudStackDeleteParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *V1CloudAccountsCloudStackDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
