// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1CloudConfigsAzureGetParams creates a new V1CloudConfigsAzureGetParams object
// with the default values initialized.
func NewV1CloudConfigsAzureGetParams() *V1CloudConfigsAzureGetParams {
	var ()
	return &V1CloudConfigsAzureGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1CloudConfigsAzureGetParamsWithTimeout creates a new V1CloudConfigsAzureGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1CloudConfigsAzureGetParamsWithTimeout(timeout time.Duration) *V1CloudConfigsAzureGetParams {
	var ()
	return &V1CloudConfigsAzureGetParams{

		timeout: timeout,
	}
}

// NewV1CloudConfigsAzureGetParamsWithContext creates a new V1CloudConfigsAzureGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1CloudConfigsAzureGetParamsWithContext(ctx context.Context) *V1CloudConfigsAzureGetParams {
	var ()
	return &V1CloudConfigsAzureGetParams{

		Context: ctx,
	}
}

// NewV1CloudConfigsAzureGetParamsWithHTTPClient creates a new V1CloudConfigsAzureGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1CloudConfigsAzureGetParamsWithHTTPClient(client *http.Client) *V1CloudConfigsAzureGetParams {
	var ()
	return &V1CloudConfigsAzureGetParams{
		HTTPClient: client,
	}
}

/*
V1CloudConfigsAzureGetParams contains all the parameters to send to the API endpoint
for the v1 cloud configs azure get operation typically these are written to a http.Request
*/
type V1CloudConfigsAzureGetParams struct {

	/*ConfigUID
	  Cluster's cloud config uid

	*/
	ConfigUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) WithTimeout(timeout time.Duration) *V1CloudConfigsAzureGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) WithContext(ctx context.Context) *V1CloudConfigsAzureGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) WithHTTPClient(client *http.Client) *V1CloudConfigsAzureGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigUID adds the configUID to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) WithConfigUID(configUID string) *V1CloudConfigsAzureGetParams {
	o.SetConfigUID(configUID)
	return o
}

// SetConfigUID adds the configUid to the v1 cloud configs azure get params
func (o *V1CloudConfigsAzureGetParams) SetConfigUID(configUID string) {
	o.ConfigUID = configUID
}

// WriteToRequest writes these params to a swagger request
func (o *V1CloudConfigsAzureGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param configUid
	if err := r.SetPathParam("configUid", o.ConfigUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
