// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// V1EdgeTokensUIDGetReader is a Reader for the V1EdgeTokensUIDGet structure.
type V1EdgeTokensUIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1EdgeTokensUIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1EdgeTokensUIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1EdgeTokensUIDGetOK creates a V1EdgeTokensUIDGetOK with default headers values
func NewV1EdgeTokensUIDGetOK() *V1EdgeTokensUIDGetOK {
	return &V1EdgeTokensUIDGetOK{}
}

/*
V1EdgeTokensUIDGetOK handles this case with default header values.

OK
*/
type V1EdgeTokensUIDGetOK struct {
	Payload *models.V1EdgeToken
}

func (o *V1EdgeTokensUIDGetOK) Error() string {
	return fmt.Sprintf("[GET /v1/edgehosts/tokens/{uid}][%d] v1EdgeTokensUidGetOK  %+v", 200, o.Payload)
}

func (o *V1EdgeTokensUIDGetOK) GetPayload() *models.V1EdgeToken {
	return o.Payload
}

func (o *V1EdgeTokensUIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1EdgeToken)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
