// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1HostClusterConfigUpdateReader is a Reader for the V1HostClusterConfigUpdate structure.
type V1HostClusterConfigUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1HostClusterConfigUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1HostClusterConfigUpdateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1HostClusterConfigUpdateNoContent creates a V1HostClusterConfigUpdateNoContent with default headers values
func NewV1HostClusterConfigUpdateNoContent() *V1HostClusterConfigUpdateNoContent {
	return &V1HostClusterConfigUpdateNoContent{}
}

/*
V1HostClusterConfigUpdateNoContent handles this case with default header values.

The resource was updated successfully
*/
type V1HostClusterConfigUpdateNoContent struct {
}

func (o *V1HostClusterConfigUpdateNoContent) Error() string {
	return fmt.Sprintf("[PATCH /v1/spectroclusters/{uid}/clusterConfig/hostCluster][%d] v1HostClusterConfigUpdateNoContent ", 204)
}

func (o *V1HostClusterConfigUpdateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
