// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1OverlordsSystemParams creates a new V1OverlordsSystemParams object
// with the default values initialized.
func NewV1OverlordsSystemParams() *V1OverlordsSystemParams {
	var ()
	return &V1OverlordsSystemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1OverlordsSystemParamsWithTimeout creates a new V1OverlordsSystemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1OverlordsSystemParamsWithTimeout(timeout time.Duration) *V1OverlordsSystemParams {
	var ()
	return &V1OverlordsSystemParams{

		timeout: timeout,
	}
}

// NewV1OverlordsSystemParamsWithContext creates a new V1OverlordsSystemParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1OverlordsSystemParamsWithContext(ctx context.Context) *V1OverlordsSystemParams {
	var ()
	return &V1OverlordsSystemParams{

		Context: ctx,
	}
}

// NewV1OverlordsSystemParamsWithHTTPClient creates a new V1OverlordsSystemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1OverlordsSystemParamsWithHTTPClient(client *http.Client) *V1OverlordsSystemParams {
	var ()
	return &V1OverlordsSystemParams{
		HTTPClient: client,
	}
}

/*
V1OverlordsSystemParams contains all the parameters to send to the API endpoint
for the v1 overlords system operation typically these are written to a http.Request
*/
type V1OverlordsSystemParams struct {

	/*TenantUID*/
	TenantUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 overlords system params
func (o *V1OverlordsSystemParams) WithTimeout(timeout time.Duration) *V1OverlordsSystemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 overlords system params
func (o *V1OverlordsSystemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 overlords system params
func (o *V1OverlordsSystemParams) WithContext(ctx context.Context) *V1OverlordsSystemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 overlords system params
func (o *V1OverlordsSystemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 overlords system params
func (o *V1OverlordsSystemParams) WithHTTPClient(client *http.Client) *V1OverlordsSystemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 overlords system params
func (o *V1OverlordsSystemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantUID adds the tenantUID to the v1 overlords system params
func (o *V1OverlordsSystemParams) WithTenantUID(tenantUID string) *V1OverlordsSystemParams {
	o.SetTenantUID(tenantUID)
	return o
}

// SetTenantUID adds the tenantUid to the v1 overlords system params
func (o *V1OverlordsSystemParams) SetTenantUID(tenantUID string) {
	o.TenantUID = tenantUID
}

// WriteToRequest writes these params to a swagger request
func (o *V1OverlordsSystemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantUid
	if err := r.SetPathParam("tenantUid", o.TenantUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
