// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1RolesCloneParams creates a new V1RolesCloneParams object
// with the default values initialized.
func NewV1RolesCloneParams() *V1RolesCloneParams {
	var ()
	return &V1RolesCloneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1RolesCloneParamsWithTimeout creates a new V1RolesCloneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1RolesCloneParamsWithTimeout(timeout time.Duration) *V1RolesCloneParams {
	var ()
	return &V1RolesCloneParams{

		timeout: timeout,
	}
}

// NewV1RolesCloneParamsWithContext creates a new V1RolesCloneParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1RolesCloneParamsWithContext(ctx context.Context) *V1RolesCloneParams {
	var ()
	return &V1RolesCloneParams{

		Context: ctx,
	}
}

// NewV1RolesCloneParamsWithHTTPClient creates a new V1RolesCloneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1RolesCloneParamsWithHTTPClient(client *http.Client) *V1RolesCloneParams {
	var ()
	return &V1RolesCloneParams{
		HTTPClient: client,
	}
}

/*
V1RolesCloneParams contains all the parameters to send to the API endpoint
for the v1 roles clone operation typically these are written to a http.Request
*/
type V1RolesCloneParams struct {

	/*Body*/
	Body *models.V1RoleClone
	/*UID*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 roles clone params
func (o *V1RolesCloneParams) WithTimeout(timeout time.Duration) *V1RolesCloneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 roles clone params
func (o *V1RolesCloneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 roles clone params
func (o *V1RolesCloneParams) WithContext(ctx context.Context) *V1RolesCloneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 roles clone params
func (o *V1RolesCloneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 roles clone params
func (o *V1RolesCloneParams) WithHTTPClient(client *http.Client) *V1RolesCloneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 roles clone params
func (o *V1RolesCloneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 roles clone params
func (o *V1RolesCloneParams) WithBody(body *models.V1RoleClone) *V1RolesCloneParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 roles clone params
func (o *V1RolesCloneParams) SetBody(body *models.V1RoleClone) {
	o.Body = body
}

// WithUID adds the uid to the v1 roles clone params
func (o *V1RolesCloneParams) WithUID(uid string) *V1RolesCloneParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the v1 roles clone params
func (o *V1RolesCloneParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *V1RolesCloneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
