// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1SystemConfigAwsImageUpdateParams creates a new V1SystemConfigAwsImageUpdateParams object
// with the default values initialized.
func NewV1SystemConfigAwsImageUpdateParams() *V1SystemConfigAwsImageUpdateParams {
	var ()
	return &V1SystemConfigAwsImageUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1SystemConfigAwsImageUpdateParamsWithTimeout creates a new V1SystemConfigAwsImageUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1SystemConfigAwsImageUpdateParamsWithTimeout(timeout time.Duration) *V1SystemConfigAwsImageUpdateParams {
	var ()
	return &V1SystemConfigAwsImageUpdateParams{

		timeout: timeout,
	}
}

// NewV1SystemConfigAwsImageUpdateParamsWithContext creates a new V1SystemConfigAwsImageUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1SystemConfigAwsImageUpdateParamsWithContext(ctx context.Context) *V1SystemConfigAwsImageUpdateParams {
	var ()
	return &V1SystemConfigAwsImageUpdateParams{

		Context: ctx,
	}
}

// NewV1SystemConfigAwsImageUpdateParamsWithHTTPClient creates a new V1SystemConfigAwsImageUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1SystemConfigAwsImageUpdateParamsWithHTTPClient(client *http.Client) *V1SystemConfigAwsImageUpdateParams {
	var ()
	return &V1SystemConfigAwsImageUpdateParams{
		HTTPClient: client,
	}
}

/*
V1SystemConfigAwsImageUpdateParams contains all the parameters to send to the API endpoint
for the v1 system config aws image update operation typically these are written to a http.Request
*/
type V1SystemConfigAwsImageUpdateParams struct {

	/*Body*/
	Body *models.V1SystemAwsImage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) WithTimeout(timeout time.Duration) *V1SystemConfigAwsImageUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) WithContext(ctx context.Context) *V1SystemConfigAwsImageUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) WithHTTPClient(client *http.Client) *V1SystemConfigAwsImageUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) WithBody(body *models.V1SystemAwsImage) *V1SystemConfigAwsImageUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 system config aws image update params
func (o *V1SystemConfigAwsImageUpdateParams) SetBody(body *models.V1SystemAwsImage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1SystemConfigAwsImageUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
