// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1SystemConfigVsphereImageGetParams creates a new V1SystemConfigVsphereImageGetParams object
// with the default values initialized.
func NewV1SystemConfigVsphereImageGetParams() *V1SystemConfigVsphereImageGetParams {

	return &V1SystemConfigVsphereImageGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1SystemConfigVsphereImageGetParamsWithTimeout creates a new V1SystemConfigVsphereImageGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1SystemConfigVsphereImageGetParamsWithTimeout(timeout time.Duration) *V1SystemConfigVsphereImageGetParams {

	return &V1SystemConfigVsphereImageGetParams{

		timeout: timeout,
	}
}

// NewV1SystemConfigVsphereImageGetParamsWithContext creates a new V1SystemConfigVsphereImageGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1SystemConfigVsphereImageGetParamsWithContext(ctx context.Context) *V1SystemConfigVsphereImageGetParams {

	return &V1SystemConfigVsphereImageGetParams{

		Context: ctx,
	}
}

// NewV1SystemConfigVsphereImageGetParamsWithHTTPClient creates a new V1SystemConfigVsphereImageGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1SystemConfigVsphereImageGetParamsWithHTTPClient(client *http.Client) *V1SystemConfigVsphereImageGetParams {

	return &V1SystemConfigVsphereImageGetParams{
		HTTPClient: client,
	}
}

/*
V1SystemConfigVsphereImageGetParams contains all the parameters to send to the API endpoint
for the v1 system config vsphere image get operation typically these are written to a http.Request
*/
type V1SystemConfigVsphereImageGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 system config vsphere image get params
func (o *V1SystemConfigVsphereImageGetParams) WithTimeout(timeout time.Duration) *V1SystemConfigVsphereImageGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 system config vsphere image get params
func (o *V1SystemConfigVsphereImageGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 system config vsphere image get params
func (o *V1SystemConfigVsphereImageGetParams) WithContext(ctx context.Context) *V1SystemConfigVsphereImageGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 system config vsphere image get params
func (o *V1SystemConfigVsphereImageGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 system config vsphere image get params
func (o *V1SystemConfigVsphereImageGetParams) WithHTTPClient(client *http.Client) *V1SystemConfigVsphereImageGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 system config vsphere image get params
func (o *V1SystemConfigVsphereImageGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1SystemConfigVsphereImageGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
