// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1SystemConfigSsoOidcValidateParams creates a new V1SystemConfigSsoOidcValidateParams object
// with the default values initialized.
func NewV1SystemConfigSsoOidcValidateParams() *V1SystemConfigSsoOidcValidateParams {
	var ()
	return &V1SystemConfigSsoOidcValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1SystemConfigSsoOidcValidateParamsWithTimeout creates a new V1SystemConfigSsoOidcValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1SystemConfigSsoOidcValidateParamsWithTimeout(timeout time.Duration) *V1SystemConfigSsoOidcValidateParams {
	var ()
	return &V1SystemConfigSsoOidcValidateParams{

		timeout: timeout,
	}
}

// NewV1SystemConfigSsoOidcValidateParamsWithContext creates a new V1SystemConfigSsoOidcValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1SystemConfigSsoOidcValidateParamsWithContext(ctx context.Context) *V1SystemConfigSsoOidcValidateParams {
	var ()
	return &V1SystemConfigSsoOidcValidateParams{

		Context: ctx,
	}
}

// NewV1SystemConfigSsoOidcValidateParamsWithHTTPClient creates a new V1SystemConfigSsoOidcValidateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1SystemConfigSsoOidcValidateParamsWithHTTPClient(client *http.Client) *V1SystemConfigSsoOidcValidateParams {
	var ()
	return &V1SystemConfigSsoOidcValidateParams{
		HTTPClient: client,
	}
}

/*
V1SystemConfigSsoOidcValidateParams contains all the parameters to send to the API endpoint
for the v1 system config sso oidc validate operation typically these are written to a http.Request
*/
type V1SystemConfigSsoOidcValidateParams struct {

	/*Body*/
	Body *models.V1SystemOidcClientSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) WithTimeout(timeout time.Duration) *V1SystemConfigSsoOidcValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) WithContext(ctx context.Context) *V1SystemConfigSsoOidcValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) WithHTTPClient(client *http.Client) *V1SystemConfigSsoOidcValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) WithBody(body *models.V1SystemOidcClientSpec) *V1SystemConfigSsoOidcValidateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 system config sso oidc validate params
func (o *V1SystemConfigSsoOidcValidateParams) SetBody(body *models.V1SystemOidcClientSpec) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1SystemConfigSsoOidcValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
