// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1SystemPasswordPolicyUpdateParams creates a new V1SystemPasswordPolicyUpdateParams object
// with the default values initialized.
func NewV1SystemPasswordPolicyUpdateParams() *V1SystemPasswordPolicyUpdateParams {
	var ()
	return &V1SystemPasswordPolicyUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1SystemPasswordPolicyUpdateParamsWithTimeout creates a new V1SystemPasswordPolicyUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1SystemPasswordPolicyUpdateParamsWithTimeout(timeout time.Duration) *V1SystemPasswordPolicyUpdateParams {
	var ()
	return &V1SystemPasswordPolicyUpdateParams{

		timeout: timeout,
	}
}

// NewV1SystemPasswordPolicyUpdateParamsWithContext creates a new V1SystemPasswordPolicyUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1SystemPasswordPolicyUpdateParamsWithContext(ctx context.Context) *V1SystemPasswordPolicyUpdateParams {
	var ()
	return &V1SystemPasswordPolicyUpdateParams{

		Context: ctx,
	}
}

// NewV1SystemPasswordPolicyUpdateParamsWithHTTPClient creates a new V1SystemPasswordPolicyUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1SystemPasswordPolicyUpdateParamsWithHTTPClient(client *http.Client) *V1SystemPasswordPolicyUpdateParams {
	var ()
	return &V1SystemPasswordPolicyUpdateParams{
		HTTPClient: client,
	}
}

/*
V1SystemPasswordPolicyUpdateParams contains all the parameters to send to the API endpoint
for the v1 system password policy update operation typically these are written to a http.Request
*/
type V1SystemPasswordPolicyUpdateParams struct {

	/*Body*/
	Body *models.V1SystemPasswordPolicySpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) WithTimeout(timeout time.Duration) *V1SystemPasswordPolicyUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) WithContext(ctx context.Context) *V1SystemPasswordPolicyUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) WithHTTPClient(client *http.Client) *V1SystemPasswordPolicyUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) WithBody(body *models.V1SystemPasswordPolicySpec) *V1SystemPasswordPolicyUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 system password policy update params
func (o *V1SystemPasswordPolicyUpdateParams) SetBody(body *models.V1SystemPasswordPolicySpec) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1SystemPasswordPolicyUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
