// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1SystemAdminsUIDDeleteReader is a Reader for the V1SystemAdminsUIDDelete structure.
type V1SystemAdminsUIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1SystemAdminsUIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1SystemAdminsUIDDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1SystemAdminsUIDDeleteNoContent creates a V1SystemAdminsUIDDeleteNoContent with default headers values
func NewV1SystemAdminsUIDDeleteNoContent() *V1SystemAdminsUIDDeleteNoContent {
	return &V1SystemAdminsUIDDeleteNoContent{}
}

/*
V1SystemAdminsUIDDeleteNoContent handles this case with default header values.

The resource was deleted successfully
*/
type V1SystemAdminsUIDDeleteNoContent struct {
}

func (o *V1SystemAdminsUIDDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/system/admins/{uid}][%d] v1SystemAdminsUidDeleteNoContent ", 204)
}

func (o *V1SystemAdminsUIDDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
