// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1SpectroClustersTagsGetParams creates a new V1SpectroClustersTagsGetParams object
// with the default values initialized.
func NewV1SpectroClustersTagsGetParams() *V1SpectroClustersTagsGetParams {

	return &V1SpectroClustersTagsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1SpectroClustersTagsGetParamsWithTimeout creates a new V1SpectroClustersTagsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1SpectroClustersTagsGetParamsWithTimeout(timeout time.Duration) *V1SpectroClustersTagsGetParams {

	return &V1SpectroClustersTagsGetParams{

		timeout: timeout,
	}
}

// NewV1SpectroClustersTagsGetParamsWithContext creates a new V1SpectroClustersTagsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1SpectroClustersTagsGetParamsWithContext(ctx context.Context) *V1SpectroClustersTagsGetParams {

	return &V1SpectroClustersTagsGetParams{

		Context: ctx,
	}
}

// NewV1SpectroClustersTagsGetParamsWithHTTPClient creates a new V1SpectroClustersTagsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1SpectroClustersTagsGetParamsWithHTTPClient(client *http.Client) *V1SpectroClustersTagsGetParams {

	return &V1SpectroClustersTagsGetParams{
		HTTPClient: client,
	}
}

/*
V1SpectroClustersTagsGetParams contains all the parameters to send to the API endpoint
for the v1 spectro clusters tags get operation typically these are written to a http.Request
*/
type V1SpectroClustersTagsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 spectro clusters tags get params
func (o *V1SpectroClustersTagsGetParams) WithTimeout(timeout time.Duration) *V1SpectroClustersTagsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 spectro clusters tags get params
func (o *V1SpectroClustersTagsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 spectro clusters tags get params
func (o *V1SpectroClustersTagsGetParams) WithContext(ctx context.Context) *V1SpectroClustersTagsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 spectro clusters tags get params
func (o *V1SpectroClustersTagsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 spectro clusters tags get params
func (o *V1SpectroClustersTagsGetParams) WithHTTPClient(client *http.Client) *V1SpectroClustersTagsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 spectro clusters tags get params
func (o *V1SpectroClustersTagsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1SpectroClustersTagsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
