// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// V1SystemConfigDomainCertificatesPutReader is a Reader for the V1SystemConfigDomainCertificatesPut structure.
type V1SystemConfigDomainCertificatesPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1SystemConfigDomainCertificatesPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1SystemConfigDomainCertificatesPutNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1SystemConfigDomainCertificatesPutNoContent creates a V1SystemConfigDomainCertificatesPutNoContent with default headers values
func NewV1SystemConfigDomainCertificatesPutNoContent() *V1SystemConfigDomainCertificatesPutNoContent {
	return &V1SystemConfigDomainCertificatesPutNoContent{}
}

/*
V1SystemConfigDomainCertificatesPutNoContent handles this case with default header values.

(empty)
*/
type V1SystemConfigDomainCertificatesPutNoContent struct {
	Payload models.V1Updated
}

func (o *V1SystemConfigDomainCertificatesPutNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/system/config/domain/certificates][%d] v1SystemConfigDomainCertificatesPutNoContent  %+v", 204, o.Payload)
}

func (o *V1SystemConfigDomainCertificatesPutNoContent) GetPayload() models.V1Updated {
	return o.Payload
}

func (o *V1SystemConfigDomainCertificatesPutNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
