// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// V1SystemConfigImagePullSecretGetReader is a Reader for the V1SystemConfigImagePullSecretGet structure.
type V1SystemConfigImagePullSecretGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1SystemConfigImagePullSecretGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1SystemConfigImagePullSecretGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1SystemConfigImagePullSecretGetOK creates a V1SystemConfigImagePullSecretGetOK with default headers values
func NewV1SystemConfigImagePullSecretGetOK() *V1SystemConfigImagePullSecretGetOK {
	return &V1SystemConfigImagePullSecretGetOK{}
}

/*
V1SystemConfigImagePullSecretGetOK handles this case with default header values.

OK
*/
type V1SystemConfigImagePullSecretGetOK struct {
	Payload *models.V1SystemConfigImagePullSecretSpec
}

func (o *V1SystemConfigImagePullSecretGetOK) Error() string {
	return fmt.Sprintf("[GET /v1/system/config/imagePullSecret][%d] v1SystemConfigImagePullSecretGetOK  %+v", 200, o.Payload)
}

func (o *V1SystemConfigImagePullSecretGetOK) GetPayload() *models.V1SystemConfigImagePullSecretSpec {
	return o.Payload
}

func (o *V1SystemConfigImagePullSecretGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SystemConfigImagePullSecretSpec)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
