// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1TeamsProjectRolesPutParams creates a new V1TeamsProjectRolesPutParams object
// with the default values initialized.
func NewV1TeamsProjectRolesPutParams() *V1TeamsProjectRolesPutParams {
	var ()
	return &V1TeamsProjectRolesPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1TeamsProjectRolesPutParamsWithTimeout creates a new V1TeamsProjectRolesPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1TeamsProjectRolesPutParamsWithTimeout(timeout time.Duration) *V1TeamsProjectRolesPutParams {
	var ()
	return &V1TeamsProjectRolesPutParams{

		timeout: timeout,
	}
}

// NewV1TeamsProjectRolesPutParamsWithContext creates a new V1TeamsProjectRolesPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1TeamsProjectRolesPutParamsWithContext(ctx context.Context) *V1TeamsProjectRolesPutParams {
	var ()
	return &V1TeamsProjectRolesPutParams{

		Context: ctx,
	}
}

// NewV1TeamsProjectRolesPutParamsWithHTTPClient creates a new V1TeamsProjectRolesPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1TeamsProjectRolesPutParamsWithHTTPClient(client *http.Client) *V1TeamsProjectRolesPutParams {
	var ()
	return &V1TeamsProjectRolesPutParams{
		HTTPClient: client,
	}
}

/*
V1TeamsProjectRolesPutParams contains all the parameters to send to the API endpoint
for the v1 teams project roles put operation typically these are written to a http.Request
*/
type V1TeamsProjectRolesPutParams struct {

	/*Body*/
	Body *models.V1ProjectRolesPatch
	/*UID*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) WithTimeout(timeout time.Duration) *V1TeamsProjectRolesPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) WithContext(ctx context.Context) *V1TeamsProjectRolesPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) WithHTTPClient(client *http.Client) *V1TeamsProjectRolesPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) WithBody(body *models.V1ProjectRolesPatch) *V1TeamsProjectRolesPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) SetBody(body *models.V1ProjectRolesPatch) {
	o.Body = body
}

// WithUID adds the uid to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) WithUID(uid string) *V1TeamsProjectRolesPutParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the v1 teams project roles put params
func (o *V1TeamsProjectRolesPutParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *V1TeamsProjectRolesPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
