// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1TeamsUIDTenantRolesUpdateReader is a Reader for the V1TeamsUIDTenantRolesUpdate structure.
type V1TeamsUIDTenantRolesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1TeamsUIDTenantRolesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1TeamsUIDTenantRolesUpdateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1TeamsUIDTenantRolesUpdateNoContent creates a V1TeamsUIDTenantRolesUpdateNoContent with default headers values
func NewV1TeamsUIDTenantRolesUpdateNoContent() *V1TeamsUIDTenantRolesUpdateNoContent {
	return &V1TeamsUIDTenantRolesUpdateNoContent{}
}

/*
V1TeamsUIDTenantRolesUpdateNoContent handles this case with default header values.

The resource was updated successfully
*/
type V1TeamsUIDTenantRolesUpdateNoContent struct {
}

func (o *V1TeamsUIDTenantRolesUpdateNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/teams/{uid}/roles][%d] v1TeamsUidTenantRolesUpdateNoContent ", 204)
}

func (o *V1TeamsUIDTenantRolesUpdateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
