// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1TenantsCreditAccountGetParams creates a new V1TenantsCreditAccountGetParams object
// with the default values initialized.
func NewV1TenantsCreditAccountGetParams() *V1TenantsCreditAccountGetParams {
	var ()
	return &V1TenantsCreditAccountGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1TenantsCreditAccountGetParamsWithTimeout creates a new V1TenantsCreditAccountGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1TenantsCreditAccountGetParamsWithTimeout(timeout time.Duration) *V1TenantsCreditAccountGetParams {
	var ()
	return &V1TenantsCreditAccountGetParams{

		timeout: timeout,
	}
}

// NewV1TenantsCreditAccountGetParamsWithContext creates a new V1TenantsCreditAccountGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1TenantsCreditAccountGetParamsWithContext(ctx context.Context) *V1TenantsCreditAccountGetParams {
	var ()
	return &V1TenantsCreditAccountGetParams{

		Context: ctx,
	}
}

// NewV1TenantsCreditAccountGetParamsWithHTTPClient creates a new V1TenantsCreditAccountGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1TenantsCreditAccountGetParamsWithHTTPClient(client *http.Client) *V1TenantsCreditAccountGetParams {
	var ()
	return &V1TenantsCreditAccountGetParams{
		HTTPClient: client,
	}
}

/*
V1TenantsCreditAccountGetParams contains all the parameters to send to the API endpoint
for the v1 tenants credit account get operation typically these are written to a http.Request
*/
type V1TenantsCreditAccountGetParams struct {

	/*TenantUID*/
	TenantUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) WithTimeout(timeout time.Duration) *V1TenantsCreditAccountGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) WithContext(ctx context.Context) *V1TenantsCreditAccountGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) WithHTTPClient(client *http.Client) *V1TenantsCreditAccountGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantUID adds the tenantUID to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) WithTenantUID(tenantUID string) *V1TenantsCreditAccountGetParams {
	o.SetTenantUID(tenantUID)
	return o
}

// SetTenantUID adds the tenantUid to the v1 tenants credit account get params
func (o *V1TenantsCreditAccountGetParams) SetTenantUID(tenantUID string) {
	o.TenantUID = tenantUID
}

// WriteToRequest writes these params to a swagger request
func (o *V1TenantsCreditAccountGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantUid
	if err := r.SetPathParam("tenantUid", o.TenantUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
