// Code generated by go-swagger; DO NOT EDIT.

package version1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1UsersMfaDevicesNameDeleteParams creates a new V1UsersMfaDevicesNameDeleteParams object
// with the default values initialized.
func NewV1UsersMfaDevicesNameDeleteParams() *V1UsersMfaDevicesNameDeleteParams {
	var ()
	return &V1UsersMfaDevicesNameDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1UsersMfaDevicesNameDeleteParamsWithTimeout creates a new V1UsersMfaDevicesNameDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1UsersMfaDevicesNameDeleteParamsWithTimeout(timeout time.Duration) *V1UsersMfaDevicesNameDeleteParams {
	var ()
	return &V1UsersMfaDevicesNameDeleteParams{

		timeout: timeout,
	}
}

// NewV1UsersMfaDevicesNameDeleteParamsWithContext creates a new V1UsersMfaDevicesNameDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1UsersMfaDevicesNameDeleteParamsWithContext(ctx context.Context) *V1UsersMfaDevicesNameDeleteParams {
	var ()
	return &V1UsersMfaDevicesNameDeleteParams{

		Context: ctx,
	}
}

// NewV1UsersMfaDevicesNameDeleteParamsWithHTTPClient creates a new V1UsersMfaDevicesNameDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1UsersMfaDevicesNameDeleteParamsWithHTTPClient(client *http.Client) *V1UsersMfaDevicesNameDeleteParams {
	var ()
	return &V1UsersMfaDevicesNameDeleteParams{
		HTTPClient: client,
	}
}

/*
V1UsersMfaDevicesNameDeleteParams contains all the parameters to send to the API endpoint
for the v1 users mfa devices name delete operation typically these are written to a http.Request
*/
type V1UsersMfaDevicesNameDeleteParams struct {

	/*DeviceName*/
	DeviceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) WithTimeout(timeout time.Duration) *V1UsersMfaDevicesNameDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) WithContext(ctx context.Context) *V1UsersMfaDevicesNameDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) WithHTTPClient(client *http.Client) *V1UsersMfaDevicesNameDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceName adds the deviceName to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) WithDeviceName(deviceName string) *V1UsersMfaDevicesNameDeleteParams {
	o.SetDeviceName(deviceName)
	return o
}

// SetDeviceName adds the deviceName to the v1 users mfa devices name delete params
func (o *V1UsersMfaDevicesNameDeleteParams) SetDeviceName(deviceName string) {
	o.DeviceName = deviceName
}

// WriteToRequest writes these params to a swagger request
func (o *V1UsersMfaDevicesNameDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceName
	if err := r.SetPathParam("deviceName", o.DeviceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
