// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1AzureAccountEntitySpec v1 azure account entity spec
//
// swagger:model v1.AzureAccountEntitySpec
type V1AzureAccountEntitySpec struct {

	// Contains configuration for Azure cloud
	// Enum: ["azure-china","azure-government","public"]
	ClientCloud *string `json:"clientCloud,omitempty"`

	// client Id
	ClientID string `json:"clientId,omitempty"`

	// client secret
	ClientSecret string `json:"clientSecret,omitempty"`

	// subscription Id
	SubscriptionID string `json:"subscriptionId,omitempty"`

	// tenant Id
	TenantID string `json:"tenantId,omitempty"`
}

// Validate validates this v1 azure account entity spec
func (m *V1AzureAccountEntitySpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientCloud(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var v1AzureAccountEntitySpecTypeClientCloudPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["azure-china","azure-government","public"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1AzureAccountEntitySpecTypeClientCloudPropEnum = append(v1AzureAccountEntitySpecTypeClientCloudPropEnum, v)
	}
}

const (

	// V1AzureAccountEntitySpecClientCloudAzureDashChina captures enum value "azure-china"
	V1AzureAccountEntitySpecClientCloudAzureDashChina string = "azure-china"

	// V1AzureAccountEntitySpecClientCloudAzureDashGovernment captures enum value "azure-government"
	V1AzureAccountEntitySpecClientCloudAzureDashGovernment string = "azure-government"

	// V1AzureAccountEntitySpecClientCloudPublic captures enum value "public"
	V1AzureAccountEntitySpecClientCloudPublic string = "public"
)

// prop value enum
func (m *V1AzureAccountEntitySpec) validateClientCloudEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, v1AzureAccountEntitySpecTypeClientCloudPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *V1AzureAccountEntitySpec) validateClientCloud(formats strfmt.Registry) error {
	if swag.IsZero(m.ClientCloud) { // not required
		return nil
	}

	// value enum
	if err := m.validateClientCloudEnum("clientCloud", "body", *m.ClientCloud); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 azure account entity spec based on context it is used
func (m *V1AzureAccountEntitySpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AzureAccountEntitySpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AzureAccountEntitySpec) UnmarshalBinary(b []byte) error {
	var res V1AzureAccountEntitySpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
