// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AppDeploymentTargetConfigSummary Application deployment target config summary
//
// swagger:model v1AppDeploymentTargetConfigSummary
type V1AppDeploymentTargetConfigSummary struct {

	// cluster ref
	ClusterRef *V1AppDeploymentClusterRefSummary `json:"clusterRef,omitempty"`
}

// Validate validates this v1 app deployment target config summary
func (m *V1AppDeploymentTargetConfigSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AppDeploymentTargetConfigSummary) validateClusterRef(formats strfmt.Registry) error {

	if swag.IsZero(m.ClusterRef) { // not required
		return nil
	}

	if m.ClusterRef != nil {
		if err := m.ClusterRef.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clusterRef")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1AppDeploymentTargetConfigSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AppDeploymentTargetConfigSummary) UnmarshalBinary(b []byte) error {
	var res V1AppDeploymentTargetConfigSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
