// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AwsCloudCostSummaryMonthlyCost v1 aws cloud cost summary monthly cost
//
// swagger:model v1AwsCloudCostSummaryMonthlyCost
type V1AwsCloudCostSummaryMonthlyCost struct {

	// Amount for aws cloud cost
	Amount float64 `json:"amount"`

	// Time duration for aws cloud cost
	Timestamp int64 `json:"timestamp,omitempty"`
}

// Validate validates this v1 aws cloud cost summary monthly cost
func (m *V1AwsCloudCostSummaryMonthlyCost) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 aws cloud cost summary monthly cost based on context it is used
func (m *V1AwsCloudCostSummaryMonthlyCost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AwsCloudCostSummaryMonthlyCost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AwsCloudCostSummaryMonthlyCost) UnmarshalBinary(b []byte) error {
	var res V1AwsCloudCostSummaryMonthlyCost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
