// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1AwsAPIEndpointsConfig AWS API endpoints configuration containing all partition settings
//
// swagger:model v1AwsApiEndpointsConfig
type V1AwsAPIEndpointsConfig struct {

	// Map of partition name to AWS endpoint configuration
	Partitions map[string]V1AwsPartitionEndpoints `json:"partitions,omitempty"`
}

// Validate validates this v1 aws Api endpoints config
func (m *V1AwsAPIEndpointsConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePartitions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AwsAPIEndpointsConfig) validatePartitions(formats strfmt.Registry) error {
	if swag.IsZero(m.Partitions) { // not required
		return nil
	}

	for k := range m.Partitions {

		if err := validate.Required("partitions"+"."+k, "body", m.Partitions[k]); err != nil {
			return err
		}
		if val, ok := m.Partitions[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("partitions" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("partitions" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 aws Api endpoints config based on the context it is used
func (m *V1AwsAPIEndpointsConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePartitions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AwsAPIEndpointsConfig) contextValidatePartitions(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Partitions {

		if val, ok := m.Partitions[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1AwsAPIEndpointsConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AwsAPIEndpointsConfig) UnmarshalBinary(b []byte) error {
	var res V1AwsAPIEndpointsConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
