// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ClusterTemplateSummaryStatus Provides status information for cluster templates like in use cluster which are launched using the template
//
// swagger:model v1ClusterTemplateSummaryStatus
type V1ClusterTemplateSummaryStatus struct {

	// in use clusters
	InUseClusters []*V1ObjectEntity `json:"inUseClusters"`

	// The reconciliation state of the cluster template
	State string `json:"state,omitempty"`
}

// Validate validates this v1 cluster template summary status
func (m *V1ClusterTemplateSummaryStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInUseClusters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ClusterTemplateSummaryStatus) validateInUseClusters(formats strfmt.Registry) error {
	if swag.IsZero(m.InUseClusters) { // not required
		return nil
	}

	for i := 0; i < len(m.InUseClusters); i++ {
		if swag.IsZero(m.InUseClusters[i]) { // not required
			continue
		}

		if m.InUseClusters[i] != nil {
			if err := m.InUseClusters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inUseClusters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inUseClusters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 cluster template summary status based on the context it is used
func (m *V1ClusterTemplateSummaryStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInUseClusters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ClusterTemplateSummaryStatus) contextValidateInUseClusters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InUseClusters); i++ {

		if m.InUseClusters[i] != nil {

			if swag.IsZero(m.InUseClusters[i]) { // not required
				return nil
			}

			if err := m.InUseClusters[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inUseClusters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inUseClusters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1ClusterTemplateSummaryStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ClusterTemplateSummaryStatus) UnmarshalBinary(b []byte) error {
	var res V1ClusterTemplateSummaryStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
