// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1ClusterPreference cluster preference
//
// swagger:model v1ClusterPreference
type V1ClusterPreference struct {

	// clusters cleanup interval post deletion
	ArchivalIntervalInHour int64 `json:"archivalIntervalInHour,omitempty"`

	// clusters deleted before delete period are eligible for cleanup
	DeletePeriodInHour int64 `json:"deletePeriodInHour,omitempty"`

	// clusters health poll interval
	// Maximum: 60
	// Minimum: 3
	HealthPollIntervalInMinutes int64 `json:"healthPollIntervalInMinutes,omitempty"`

	// clusters state and consistency monitor
	MonitorIntervalInMinutes int64 `json:"monitorIntervalInMinutes,omitempty"`
}

// Validate validates this v1 cluster preference
func (m *V1ClusterPreference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHealthPollIntervalInMinutes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ClusterPreference) validateHealthPollIntervalInMinutes(formats strfmt.Registry) error {
	if swag.IsZero(m.HealthPollIntervalInMinutes) { // not required
		return nil
	}

	if err := validate.MinimumInt("healthPollIntervalInMinutes", "body", m.HealthPollIntervalInMinutes, 3, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("healthPollIntervalInMinutes", "body", m.HealthPollIntervalInMinutes, 60, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 cluster preference based on context it is used
func (m *V1ClusterPreference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1ClusterPreference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ClusterPreference) UnmarshalBinary(b []byte) error {
	var res V1ClusterPreference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
