// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1EdgeTokenSpecUpdate Edge token spec to be updated
//
// swagger:model v1EdgeTokenSpecUpdate
type V1EdgeTokenSpecUpdate struct {

	// Default project where the edgehost will be placed on the token authorization
	DefaultProjectUID string `json:"defaultProjectUid,omitempty"`

	// expiry
	// Format: date-time
	Expiry V1Time `json:"expiry,omitempty"`
}

// Validate validates this v1 edge token spec update
func (m *V1EdgeTokenSpecUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiry(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EdgeTokenSpecUpdate) validateExpiry(formats strfmt.Registry) error {

	if swag.IsZero(m.Expiry) { // not required
		return nil
	}

	if err := m.Expiry.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("expiry")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1EdgeTokenSpecUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EdgeTokenSpecUpdate) UnmarshalBinary(b []byte) error {
	var res V1EdgeTokenSpecUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
