// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1EdgeMachinePoolCloudConfigEntity v1 edge machine pool cloud config entity
//
// swagger:model v1EdgeMachinePoolCloudConfigEntity
type V1EdgeMachinePoolCloudConfigEntity struct {

	// edge hosts
	// Required: true
	// Unique: true
	EdgeHosts []*V1EdgeMachinePoolHostEntity `json:"edgeHosts"`
}

// Validate validates this v1 edge machine pool cloud config entity
func (m *V1EdgeMachinePoolCloudConfigEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEdgeHosts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EdgeMachinePoolCloudConfigEntity) validateEdgeHosts(formats strfmt.Registry) error {

	if err := validate.Required("edgeHosts", "body", m.EdgeHosts); err != nil {
		return err
	}

	if err := validate.UniqueItems("edgeHosts", "body", m.EdgeHosts); err != nil {
		return err
	}

	for i := 0; i < len(m.EdgeHosts); i++ {
		if swag.IsZero(m.EdgeHosts[i]) { // not required
			continue
		}

		if m.EdgeHosts[i] != nil {
			if err := m.EdgeHosts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("edgeHosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1EdgeMachinePoolCloudConfigEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EdgeMachinePoolCloudConfigEntity) UnmarshalBinary(b []byte) error {
	var res V1EdgeMachinePoolCloudConfigEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
