// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1EksMachinePoolConfig v1 eks machine pool config
//
// swagger:model v1EksMachinePoolConfig
type V1EksMachinePoolConfig struct {

	// Custom annotations for CAPI machine objects and nodes.
	//
	AdditionalAnnotations map[string]string `json:"additionalAnnotations,omitempty"`

	// additionalLabels
	AdditionalLabels map[string]string `json:"additionalLabels,omitempty"`

	// AdditionalTags is an optional set of tags to add to resources managed by the provider, in addition to the ones added by default. For eg., tags for EKS nodeGroup or EKS NodegroupIAMRole
	AdditionalTags map[string]string `json:"additionalTags,omitempty"`

	// ami type
	AmiType string `json:"amiType,omitempty"`

	// aws launch template
	AwsLaunchTemplate *V1AwsLaunchTemplate `json:"awsLaunchTemplate,omitempty"`

	// AZs is only used for dynamic placement
	Azs []string `json:"azs"`

	// EC2 instance capacity type
	// Enum: ["on-demand","spot"]
	CapacityType *string `json:"capacityType,omitempty"`

	// flag to know if aws launch template is enabled
	EnableAwsLaunchTemplate bool `json:"enableAwsLaunchTemplate,omitempty"`

	// instance config
	InstanceConfig *V1InstanceConfig `json:"instanceConfig,omitempty"`

	// instance type
	InstanceType string `json:"instanceType,omitempty"`

	// whether this pool is for control plane
	// Required: true
	IsControlPlane *bool `json:"isControlPlane"`

	// labels for this pool, example: control-plane/worker, gpu, windows
	Labels []string `json:"labels"`

	// machine pool properties
	MachinePoolProperties *V1MachinePoolProperties `json:"machinePoolProperties,omitempty"`

	// max size of the pool, for scaling
	MaxSize int32 `json:"maxSize,omitempty"`

	// min size of the pool, for scaling
	MinSize int32 `json:"minSize,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// Minimum number of seconds a node should be Ready, before the next node is selected for repave. Applicable only for workerpools in infrastructure cluster
	NodeRepaveInterval int32 `json:"nodeRepaveInterval,omitempty"`

	// YAML config for kubeletExtraArgs, preKubeadmCommands, postKubeadmCommands.
	// Overrides pack-level settings. Worker pools only.
	//
	OverrideKubeadmConfiguration string `json:"overrideKubeadmConfiguration,omitempty"`

	// rootDeviceSize in GBs
	RootDeviceSize int64 `json:"rootDeviceSize,omitempty"`

	// size of the pool, number of machines
	Size int32 `json:"size,omitempty"`

	// SpotMarketOptions allows users to configure instances to be run using AWS Spot instances.
	SpotMarketOptions *V1SpotMarketOptions `json:"spotMarketOptions,omitempty"`

	// AZ to subnet mapping filled by ally from hubble SubnetIDs ["us-west-2d"] = "subnet-079b6061" This field is optional If we don't provide a subnetId then by default the first private subnet from the AZ will be picked up for deployment
	SubnetIds map[string]string `json:"subnetIds,omitempty"`

	// control plane or worker taints
	// Unique: true
	Taints []*V1Taint `json:"taints"`

	// rolling update strategy for this machinepool if not specified, will use ScaleOut
	UpdateStrategy *V1UpdateStrategy `json:"updateStrategy,omitempty"`

	// if IsControlPlane==true && useControlPlaneAsWorker==true, then will remove control plane taint this will not be used for worker pools
	UseControlPlaneAsWorker bool `json:"useControlPlaneAsWorker"`
}

// Validate validates this v1 eks machine pool config
func (m *V1EksMachinePoolConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAwsLaunchTemplate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCapacityType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIsControlPlane(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMachinePoolProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpotMarketOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaints(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateStrategy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EksMachinePoolConfig) validateAwsLaunchTemplate(formats strfmt.Registry) error {
	if swag.IsZero(m.AwsLaunchTemplate) { // not required
		return nil
	}

	if m.AwsLaunchTemplate != nil {
		if err := m.AwsLaunchTemplate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("awsLaunchTemplate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("awsLaunchTemplate")
			}
			return err
		}
	}

	return nil
}

var v1EksMachinePoolConfigTypeCapacityTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["on-demand","spot"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1EksMachinePoolConfigTypeCapacityTypePropEnum = append(v1EksMachinePoolConfigTypeCapacityTypePropEnum, v)
	}
}

const (

	// V1EksMachinePoolConfigCapacityTypeOnDashDemand captures enum value "on-demand"
	V1EksMachinePoolConfigCapacityTypeOnDashDemand string = "on-demand"

	// V1EksMachinePoolConfigCapacityTypeSpot captures enum value "spot"
	V1EksMachinePoolConfigCapacityTypeSpot string = "spot"
)

// prop value enum
func (m *V1EksMachinePoolConfig) validateCapacityTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, v1EksMachinePoolConfigTypeCapacityTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *V1EksMachinePoolConfig) validateCapacityType(formats strfmt.Registry) error {
	if swag.IsZero(m.CapacityType) { // not required
		return nil
	}

	// value enum
	if err := m.validateCapacityTypeEnum("capacityType", "body", *m.CapacityType); err != nil {
		return err
	}

	return nil
}

func (m *V1EksMachinePoolConfig) validateInstanceConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceConfig) { // not required
		return nil
	}

	if m.InstanceConfig != nil {
		if err := m.InstanceConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instanceConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instanceConfig")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) validateIsControlPlane(formats strfmt.Registry) error {

	if err := validate.Required("isControlPlane", "body", m.IsControlPlane); err != nil {
		return err
	}

	return nil
}

func (m *V1EksMachinePoolConfig) validateMachinePoolProperties(formats strfmt.Registry) error {
	if swag.IsZero(m.MachinePoolProperties) { // not required
		return nil
	}

	if m.MachinePoolProperties != nil {
		if err := m.MachinePoolProperties.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("machinePoolProperties")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("machinePoolProperties")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) validateSpotMarketOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.SpotMarketOptions) { // not required
		return nil
	}

	if m.SpotMarketOptions != nil {
		if err := m.SpotMarketOptions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("spotMarketOptions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("spotMarketOptions")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) validateTaints(formats strfmt.Registry) error {
	if swag.IsZero(m.Taints) { // not required
		return nil
	}

	if err := validate.UniqueItems("taints", "body", m.Taints); err != nil {
		return err
	}

	for i := 0; i < len(m.Taints); i++ {
		if swag.IsZero(m.Taints[i]) { // not required
			continue
		}

		if m.Taints[i] != nil {
			if err := m.Taints[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("taints" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("taints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1EksMachinePoolConfig) validateUpdateStrategy(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateStrategy) { // not required
		return nil
	}

	if m.UpdateStrategy != nil {
		if err := m.UpdateStrategy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateStrategy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updateStrategy")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 eks machine pool config based on the context it is used
func (m *V1EksMachinePoolConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAwsLaunchTemplate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstanceConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMachinePoolProperties(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSpotMarketOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTaints(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdateStrategy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EksMachinePoolConfig) contextValidateAwsLaunchTemplate(ctx context.Context, formats strfmt.Registry) error {

	if m.AwsLaunchTemplate != nil {

		if swag.IsZero(m.AwsLaunchTemplate) { // not required
			return nil
		}

		if err := m.AwsLaunchTemplate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("awsLaunchTemplate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("awsLaunchTemplate")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) contextValidateInstanceConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.InstanceConfig != nil {

		if swag.IsZero(m.InstanceConfig) { // not required
			return nil
		}

		if err := m.InstanceConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instanceConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instanceConfig")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) contextValidateMachinePoolProperties(ctx context.Context, formats strfmt.Registry) error {

	if m.MachinePoolProperties != nil {

		if swag.IsZero(m.MachinePoolProperties) { // not required
			return nil
		}

		if err := m.MachinePoolProperties.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("machinePoolProperties")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("machinePoolProperties")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) contextValidateSpotMarketOptions(ctx context.Context, formats strfmt.Registry) error {

	if m.SpotMarketOptions != nil {

		if swag.IsZero(m.SpotMarketOptions) { // not required
			return nil
		}

		if err := m.SpotMarketOptions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("spotMarketOptions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("spotMarketOptions")
			}
			return err
		}
	}

	return nil
}

func (m *V1EksMachinePoolConfig) contextValidateTaints(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Taints); i++ {

		if m.Taints[i] != nil {

			if swag.IsZero(m.Taints[i]) { // not required
				return nil
			}

			if err := m.Taints[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("taints" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("taints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1EksMachinePoolConfig) contextValidateUpdateStrategy(ctx context.Context, formats strfmt.Registry) error {

	if m.UpdateStrategy != nil {

		if swag.IsZero(m.UpdateStrategy) { // not required
			return nil
		}

		if err := m.UpdateStrategy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateStrategy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updateStrategy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1EksMachinePoolConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EksMachinePoolConfig) UnmarshalBinary(b []byte) error {
	var res V1EksMachinePoolConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
