// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1GeolocationLatlong Geolocation Latlong entity
//
// swagger:model v1GeolocationLatlong
type V1GeolocationLatlong struct {

	// Latitude of a resource
	Latitude float64 `json:"latitude"`

	// Longitude of a resource
	Longitude float64 `json:"longitude"`
}

// Validate validates this v1 geolocation latlong
func (m *V1GeolocationLatlong) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 geolocation latlong based on context it is used
func (m *V1GeolocationLatlong) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GeolocationLatlong) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GeolocationLatlong) UnmarshalBinary(b []byte) error {
	var res V1GeolocationLatlong
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
