// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1HostClusterConfigEntity v1 host cluster config entity
//
// swagger:model v1HostClusterConfigEntity
type V1HostClusterConfigEntity struct {

	// host cluster config
	HostClusterConfig *V1HostClusterConfig `json:"hostClusterConfig,omitempty"`
}

// Validate validates this v1 host cluster config entity
func (m *V1HostClusterConfigEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHostClusterConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1HostClusterConfigEntity) validateHostClusterConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.HostClusterConfig) { // not required
		return nil
	}

	if m.HostClusterConfig != nil {
		if err := m.HostClusterConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hostClusterConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("hostClusterConfig")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 host cluster config entity based on the context it is used
func (m *V1HostClusterConfigEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHostClusterConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1HostClusterConfigEntity) contextValidateHostClusterConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.HostClusterConfig != nil {

		if swag.IsZero(m.HostClusterConfig) { // not required
			return nil
		}

		if err := m.HostClusterConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hostClusterConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("hostClusterConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1HostClusterConfigEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1HostClusterConfigEntity) UnmarshalBinary(b []byte) error {
	var res V1HostClusterConfigEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
