// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ImportEdgeHostConfig v1 import edge host config
//
// swagger:model v1ImportEdgeHostConfig
type V1ImportEdgeHostConfig struct {

	// Deprecated. Use 'edgeHostUids' field
	EdgeHostUID string `json:"edgeHostUid,omitempty"`

	// edge host uids
	EdgeHostUids []string `json:"edgeHostUids"`
}

// Validate validates this v1 import edge host config
func (m *V1ImportEdgeHostConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 import edge host config based on context it is used
func (m *V1ImportEdgeHostConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1ImportEdgeHostConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ImportEdgeHostConfig) UnmarshalBinary(b []byte) error {
	var res V1ImportEdgeHostConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
