// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1ImagePullSecretPropagationClustersUpdate Update cluster exclude flags for propagation rollup
//
// swagger:model v1ImagePullSecretPropagationClustersUpdate
type V1ImagePullSecretPropagationClustersUpdate struct {

	// cluster uids
	// Required: true
	ClusterUids []string `json:"clusterUids"`

	// exclude
	// Required: true
	Exclude *bool `json:"exclude"`
}

// Validate validates this v1 image pull secret propagation clusters update
func (m *V1ImagePullSecretPropagationClustersUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterUids(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExclude(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ImagePullSecretPropagationClustersUpdate) validateClusterUids(formats strfmt.Registry) error {

	if err := validate.Required("clusterUids", "body", m.ClusterUids); err != nil {
		return err
	}

	return nil
}

func (m *V1ImagePullSecretPropagationClustersUpdate) validateExclude(formats strfmt.Registry) error {

	if err := validate.Required("exclude", "body", m.Exclude); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 image pull secret propagation clusters update based on context it is used
func (m *V1ImagePullSecretPropagationClustersUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1ImagePullSecretPropagationClustersUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ImagePullSecretPropagationClustersUpdate) UnmarshalBinary(b []byte) error {
	var res V1ImagePullSecretPropagationClustersUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
