// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SpectroClusterAssetFrpKubeConfig Cluster asset Frp Kube Config
//
// swagger:model v1SpectroClusterAssetFrpKubeConfig
type V1SpectroClusterAssetFrpKubeConfig struct {

	// frp kubeconfig
	FrpKubeconfig string `json:"frpKubeconfig,omitempty"`
}

// Validate validates this v1 spectro cluster asset frp kube config
func (m *V1SpectroClusterAssetFrpKubeConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 spectro cluster asset frp kube config based on context it is used
func (m *V1SpectroClusterAssetFrpKubeConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SpectroClusterAssetFrpKubeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SpectroClusterAssetFrpKubeConfig) UnmarshalBinary(b []byte) error {
	var res V1SpectroClusterAssetFrpKubeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
