// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SystemFtpSpec system ftp config spec
//
// swagger:model v1SystemFtpSpec
type V1SystemFtpSpec struct {

	// dir
	Dir string `json:"dir"`

	// password
	Password string `json:"password"`

	// server
	Server string `json:"server"`

	// username
	Username string `json:"username"`
}

// Validate validates this v1 system ftp spec
func (m *V1SystemFtpSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SystemFtpSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SystemFtpSpec) UnmarshalBinary(b []byte) error {
	var res V1SystemFtpSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
