// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SpectroTunnelStatus SpectroTunnelStatus is the status of the tunnel
//
// swagger:model v1SpectroTunnelStatus
type V1SpectroTunnelStatus struct {

	// SshStatus is the status of the ssh tunnel
	SSH *V1SSHTunnelStatus `json:"ssh,omitempty"`
}

// Validate validates this v1 spectro tunnel status
func (m *V1SpectroTunnelStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSSH(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SpectroTunnelStatus) validateSSH(formats strfmt.Registry) error {
	if swag.IsZero(m.SSH) { // not required
		return nil
	}

	if m.SSH != nil {
		if err := m.SSH.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ssh")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ssh")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 spectro tunnel status based on the context it is used
func (m *V1SpectroTunnelStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSSH(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SpectroTunnelStatus) contextValidateSSH(ctx context.Context, formats strfmt.Registry) error {

	if m.SSH != nil {

		if swag.IsZero(m.SSH) { // not required
			return nil
		}

		if err := m.SSH.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ssh")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ssh")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1SpectroTunnelStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SpectroTunnelStatus) UnmarshalBinary(b []byte) error {
	var res V1SpectroTunnelStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
