// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TenantEnableClusterGroup Enable or Disable cluster group for a tenant
//
// swagger:model v1TenantEnableClusterGroup
type V1TenantEnableClusterGroup struct {

	// hide system cluster groups
	HideSystemClusterGroups bool `json:"hideSystemClusterGroups"`

	// Deprecated. Use hideSystemClusterGroups field
	IsClusterGroupEnabled bool `json:"isClusterGroupEnabled"`
}

// Validate validates this v1 tenant enable cluster group
func (m *V1TenantEnableClusterGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 tenant enable cluster group based on context it is used
func (m *V1TenantEnableClusterGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TenantEnableClusterGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TenantEnableClusterGroup) UnmarshalBinary(b []byte) error {
	var res V1TenantEnableClusterGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
