// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1VMKVMTimer v1 Vm k Vm timer
//
// swagger:model v1VmKVmTimer
type V1VMKVMTimer struct {

	// Enabled set to false makes sure that the machine type or a preset can't add the timer. Defaults to true.
	Present bool `json:"present,omitempty"`
}

// Validate validates this v1 Vm k Vm timer
func (m *V1VMKVMTimer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 Vm k Vm timer based on context it is used
func (m *V1VMKVMTimer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1VMKVMTimer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1VMKVMTimer) UnmarshalBinary(b []byte) error {
	var res V1VMKVMTimer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
