// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1VMSEV v1 Vm s e v
//
// swagger:model v1VmSEV
type V1VMSEV interface{}
