// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1VMDataVolumeBlankImage DataVolumeBlankImage provides the parameters to create a new raw blank image for the PVC
//
// swagger:model v1VmDataVolumeBlankImage
type V1VMDataVolumeBlankImage interface{}
