// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1VMWatchdog Named watchdog device.
//
// swagger:model v1VmWatchdog
type V1VMWatchdog struct {

	// i6300esb
	I6300esb *V1VMI6300ESBWatchdog `json:"i6300esb,omitempty"`

	// Name of the watchdog.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this v1 Vm watchdog
func (m *V1VMWatchdog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateI6300esb(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1VMWatchdog) validateI6300esb(formats strfmt.Registry) error {

	if swag.IsZero(m.I6300esb) { // not required
		return nil
	}

	if m.I6300esb != nil {
		if err := m.I6300esb.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("i6300esb")
			}
			return err
		}
	}

	return nil
}

func (m *V1VMWatchdog) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1VMWatchdog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1VMWatchdog) UnmarshalBinary(b []byte) error {
	var res V1VMWatchdog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
