// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1EdgeMount Edge mounts
//
// swagger:model v1EdgeMount
type V1EdgeMount struct {

	// container path
	ContainerPath string `json:"containerPath,omitempty"`

	// host path
	HostPath string `json:"hostPath,omitempty"`

	// readonly
	Readonly bool `json:"readonly,omitempty"`
}

// Validate validates this v1 edge mount
func (m *V1EdgeMount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1EdgeMount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EdgeMount) UnmarshalBinary(b []byte) error {
	var res V1EdgeMount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
