// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1PrivateCloudRateConfig Private cloud rate config
//
// swagger:model v1PrivateCloudRateConfig
type V1PrivateCloudRateConfig struct {

	// cpu unit price per hour
	CPUUnitPricePerHour float64 `json:"cpuUnitPricePerHour,omitempty"`

	// gpu unit price per hour
	GpuUnitPricePerHour float64 `json:"gpuUnitPricePerHour,omitempty"`

	// memory unit price gi b per hour
	MemoryUnitPriceGiBPerHour float64 `json:"memoryUnitPriceGiBPerHour,omitempty"`

	// storage unit price gi b per hour
	StorageUnitPriceGiBPerHour float64 `json:"storageUnitPriceGiBPerHour,omitempty"`
}

// Validate validates this v1 private cloud rate config
func (m *V1PrivateCloudRateConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1PrivateCloudRateConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1PrivateCloudRateConfig) UnmarshalBinary(b []byte) error {
	var res V1PrivateCloudRateConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
