// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-api-go/models"
)

// V1AzureVhdURLReader is a Reader for the V1AzureVhdURL structure.
type V1AzureVhdURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AzureVhdURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AzureVhdURLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1AzureVhdURLOK creates a V1AzureVhdURLOK with default headers values
func NewV1AzureVhdURLOK() *V1AzureVhdURLOK {
	return &V1AzureVhdURLOK{}
}

/*V1AzureVhdURLOK handles this case with default header values.

(empty)
*/
type V1AzureVhdURLOK struct {
	Payload *models.V1AzureVhdURLEntity
}

func (o *V1AzureVhdURLOK) Error() string {
	return fmt.Sprintf("[GET /v1/clouds/azure/vhds/{vhd}/url][%d] v1AzureVhdUrlOK  %+v", 200, o.Payload)
}

func (o *V1AzureVhdURLOK) GetPayload() *models.V1AzureVhdURLEntity {
	return o.Payload
}

func (o *V1AzureVhdURLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1AzureVhdURLEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
