// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1AuthOrgsParams creates a new V1AuthOrgsParams object
// with the default values initialized.
func NewV1AuthOrgsParams() *V1AuthOrgsParams {

	return &V1AuthOrgsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1AuthOrgsParamsWithTimeout creates a new V1AuthOrgsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1AuthOrgsParamsWithTimeout(timeout time.Duration) *V1AuthOrgsParams {

	return &V1AuthOrgsParams{

		timeout: timeout,
	}
}

// NewV1AuthOrgsParamsWithContext creates a new V1AuthOrgsParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1AuthOrgsParamsWithContext(ctx context.Context) *V1AuthOrgsParams {

	return &V1AuthOrgsParams{

		Context: ctx,
	}
}

// NewV1AuthOrgsParamsWithHTTPClient creates a new V1AuthOrgsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1AuthOrgsParamsWithHTTPClient(client *http.Client) *V1AuthOrgsParams {

	return &V1AuthOrgsParams{
		HTTPClient: client,
	}
}

/*
V1AuthOrgsParams contains all the parameters to send to the API endpoint
for the v1 auth orgs operation typically these are written to a http.Request
*/
type V1AuthOrgsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 auth orgs params
func (o *V1AuthOrgsParams) WithTimeout(timeout time.Duration) *V1AuthOrgsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 auth orgs params
func (o *V1AuthOrgsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 auth orgs params
func (o *V1AuthOrgsParams) WithContext(ctx context.Context) *V1AuthOrgsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 auth orgs params
func (o *V1AuthOrgsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 auth orgs params
func (o *V1AuthOrgsParams) WithHTTPClient(client *http.Client) *V1AuthOrgsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 auth orgs params
func (o *V1AuthOrgsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1AuthOrgsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
