// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1CloudConfigsCoxEdgeMachinePoolCreateParams creates a new V1CloudConfigsCoxEdgeMachinePoolCreateParams object
// with the default values initialized.
func NewV1CloudConfigsCoxEdgeMachinePoolCreateParams() *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	var ()
	return &V1CloudConfigsCoxEdgeMachinePoolCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1CloudConfigsCoxEdgeMachinePoolCreateParamsWithTimeout creates a new V1CloudConfigsCoxEdgeMachinePoolCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1CloudConfigsCoxEdgeMachinePoolCreateParamsWithTimeout(timeout time.Duration) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	var ()
	return &V1CloudConfigsCoxEdgeMachinePoolCreateParams{

		timeout: timeout,
	}
}

// NewV1CloudConfigsCoxEdgeMachinePoolCreateParamsWithContext creates a new V1CloudConfigsCoxEdgeMachinePoolCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1CloudConfigsCoxEdgeMachinePoolCreateParamsWithContext(ctx context.Context) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	var ()
	return &V1CloudConfigsCoxEdgeMachinePoolCreateParams{

		Context: ctx,
	}
}

// NewV1CloudConfigsCoxEdgeMachinePoolCreateParamsWithHTTPClient creates a new V1CloudConfigsCoxEdgeMachinePoolCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1CloudConfigsCoxEdgeMachinePoolCreateParamsWithHTTPClient(client *http.Client) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	var ()
	return &V1CloudConfigsCoxEdgeMachinePoolCreateParams{
		HTTPClient: client,
	}
}

/*
V1CloudConfigsCoxEdgeMachinePoolCreateParams contains all the parameters to send to the API endpoint
for the v1 cloud configs cox edge machine pool create operation typically these are written to a http.Request
*/
type V1CloudConfigsCoxEdgeMachinePoolCreateParams struct {

	/*Body*/
	Body *models.V1CoxEdgeMachinePoolConfigEntity
	/*ConfigUID
	  Cluster's cloud config uid

	*/
	ConfigUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) WithTimeout(timeout time.Duration) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) WithContext(ctx context.Context) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) WithHTTPClient(client *http.Client) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) WithBody(body *models.V1CoxEdgeMachinePoolConfigEntity) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) SetBody(body *models.V1CoxEdgeMachinePoolConfigEntity) {
	o.Body = body
}

// WithConfigUID adds the configUID to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) WithConfigUID(configUID string) *V1CloudConfigsCoxEdgeMachinePoolCreateParams {
	o.SetConfigUID(configUID)
	return o
}

// SetConfigUID adds the configUid to the v1 cloud configs cox edge machine pool create params
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) SetConfigUID(configUID string) {
	o.ConfigUID = configUID
}

// WriteToRequest writes these params to a swagger request
func (o *V1CloudConfigsCoxEdgeMachinePoolCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param configUid
	if err := r.SetPathParam("configUid", o.ConfigUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
