// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1CustomCloudTypeLogoUpdateReader is a Reader for the V1CustomCloudTypeLogoUpdate structure.
type V1CustomCloudTypeLogoUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1CustomCloudTypeLogoUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV1CustomCloudTypeLogoUpdateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1CustomCloudTypeLogoUpdateNoContent creates a V1CustomCloudTypeLogoUpdateNoContent with default headers values
func NewV1CustomCloudTypeLogoUpdateNoContent() *V1CustomCloudTypeLogoUpdateNoContent {
	return &V1CustomCloudTypeLogoUpdateNoContent{}
}

/*V1CustomCloudTypeLogoUpdateNoContent handles this case with default header values.

Ok response without content
*/
type V1CustomCloudTypeLogoUpdateNoContent struct {
	/*Audit uid for the request
	 */
	AuditUID string
}

func (o *V1CustomCloudTypeLogoUpdateNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/clouds/cloudTypes/{cloudType}/logo][%d] v1CustomCloudTypeLogoUpdateNoContent ", 204)
}

func (o *V1CustomCloudTypeLogoUpdateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header AuditUid
	o.AuditUID = response.GetHeader("AuditUid")

	return nil
}
