// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1CustomCloudTypeClusterTemplateGetParams creates a new V1CustomCloudTypeClusterTemplateGetParams object
// with the default values initialized.
func NewV1CustomCloudTypeClusterTemplateGetParams() *V1CustomCloudTypeClusterTemplateGetParams {
	var ()
	return &V1CustomCloudTypeClusterTemplateGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1CustomCloudTypeClusterTemplateGetParamsWithTimeout creates a new V1CustomCloudTypeClusterTemplateGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1CustomCloudTypeClusterTemplateGetParamsWithTimeout(timeout time.Duration) *V1CustomCloudTypeClusterTemplateGetParams {
	var ()
	return &V1CustomCloudTypeClusterTemplateGetParams{

		timeout: timeout,
	}
}

// NewV1CustomCloudTypeClusterTemplateGetParamsWithContext creates a new V1CustomCloudTypeClusterTemplateGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1CustomCloudTypeClusterTemplateGetParamsWithContext(ctx context.Context) *V1CustomCloudTypeClusterTemplateGetParams {
	var ()
	return &V1CustomCloudTypeClusterTemplateGetParams{

		Context: ctx,
	}
}

// NewV1CustomCloudTypeClusterTemplateGetParamsWithHTTPClient creates a new V1CustomCloudTypeClusterTemplateGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1CustomCloudTypeClusterTemplateGetParamsWithHTTPClient(client *http.Client) *V1CustomCloudTypeClusterTemplateGetParams {
	var ()
	return &V1CustomCloudTypeClusterTemplateGetParams{
		HTTPClient: client,
	}
}

/*V1CustomCloudTypeClusterTemplateGetParams contains all the parameters to send to the API endpoint
for the v1 custom cloud type cluster template get operation typically these are written to a http.Request
*/
type V1CustomCloudTypeClusterTemplateGetParams struct {

	/*CloudType
	  Unique cloud type

	*/
	CloudType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) WithTimeout(timeout time.Duration) *V1CustomCloudTypeClusterTemplateGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) WithContext(ctx context.Context) *V1CustomCloudTypeClusterTemplateGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) WithHTTPClient(client *http.Client) *V1CustomCloudTypeClusterTemplateGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudType adds the cloudType to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) WithCloudType(cloudType string) *V1CustomCloudTypeClusterTemplateGetParams {
	o.SetCloudType(cloudType)
	return o
}

// SetCloudType adds the cloudType to the v1 custom cloud type cluster template get params
func (o *V1CustomCloudTypeClusterTemplateGetParams) SetCloudType(cloudType string) {
	o.CloudType = cloudType
}

// WriteToRequest writes these params to a swagger request
func (o *V1CustomCloudTypeClusterTemplateGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cloudType
	if err := r.SetPathParam("cloudType", o.CloudType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
