// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1CloudConfigsCustomPoolMachinesUIDDeleteParams creates a new V1CloudConfigsCustomPoolMachinesUIDDeleteParams object
// with the default values initialized.
func NewV1CloudConfigsCustomPoolMachinesUIDDeleteParams() *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	var ()
	return &V1CloudConfigsCustomPoolMachinesUIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1CloudConfigsCustomPoolMachinesUIDDeleteParamsWithTimeout creates a new V1CloudConfigsCustomPoolMachinesUIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1CloudConfigsCustomPoolMachinesUIDDeleteParamsWithTimeout(timeout time.Duration) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	var ()
	return &V1CloudConfigsCustomPoolMachinesUIDDeleteParams{

		timeout: timeout,
	}
}

// NewV1CloudConfigsCustomPoolMachinesUIDDeleteParamsWithContext creates a new V1CloudConfigsCustomPoolMachinesUIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1CloudConfigsCustomPoolMachinesUIDDeleteParamsWithContext(ctx context.Context) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	var ()
	return &V1CloudConfigsCustomPoolMachinesUIDDeleteParams{

		Context: ctx,
	}
}

// NewV1CloudConfigsCustomPoolMachinesUIDDeleteParamsWithHTTPClient creates a new V1CloudConfigsCustomPoolMachinesUIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1CloudConfigsCustomPoolMachinesUIDDeleteParamsWithHTTPClient(client *http.Client) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	var ()
	return &V1CloudConfigsCustomPoolMachinesUIDDeleteParams{
		HTTPClient: client,
	}
}

/*
V1CloudConfigsCustomPoolMachinesUIDDeleteParams contains all the parameters to send to the API endpoint
for the v1 cloud configs custom pool machines Uid delete operation typically these are written to a http.Request
*/
type V1CloudConfigsCustomPoolMachinesUIDDeleteParams struct {

	/*CloudType
	  Cluster's cloud type

	*/
	CloudType string
	/*ConfigUID
	  Cluster's cloud config uid

	*/
	ConfigUID string
	/*MachinePoolName
	  Machine pool name

	*/
	MachinePoolName string
	/*MachineUID
	  Machine uid

	*/
	MachineUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithTimeout(timeout time.Duration) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithContext(ctx context.Context) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithHTTPClient(client *http.Client) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudType adds the cloudType to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithCloudType(cloudType string) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetCloudType(cloudType)
	return o
}

// SetCloudType adds the cloudType to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetCloudType(cloudType string) {
	o.CloudType = cloudType
}

// WithConfigUID adds the configUID to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithConfigUID(configUID string) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetConfigUID(configUID)
	return o
}

// SetConfigUID adds the configUid to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetConfigUID(configUID string) {
	o.ConfigUID = configUID
}

// WithMachinePoolName adds the machinePoolName to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithMachinePoolName(machinePoolName string) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetMachinePoolName(machinePoolName)
	return o
}

// SetMachinePoolName adds the machinePoolName to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetMachinePoolName(machinePoolName string) {
	o.MachinePoolName = machinePoolName
}

// WithMachineUID adds the machineUID to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WithMachineUID(machineUID string) *V1CloudConfigsCustomPoolMachinesUIDDeleteParams {
	o.SetMachineUID(machineUID)
	return o
}

// SetMachineUID adds the machineUid to the v1 cloud configs custom pool machines Uid delete params
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) SetMachineUID(machineUID string) {
	o.MachineUID = machineUID
}

// WriteToRequest writes these params to a swagger request
func (o *V1CloudConfigsCustomPoolMachinesUIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cloudType
	if err := r.SetPathParam("cloudType", o.CloudType); err != nil {
		return err
	}

	// path param configUid
	if err := r.SetPathParam("configUid", o.ConfigUID); err != nil {
		return err
	}

	// path param machinePoolName
	if err := r.SetPathParam("machinePoolName", o.MachinePoolName); err != nil {
		return err
	}

	// path param machineUid
	if err := r.SetPathParam("machineUid", o.MachineUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
