// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1OverlordsVsphereOvaGetParams creates a new V1OverlordsVsphereOvaGetParams object
// with the default values initialized.
func NewV1OverlordsVsphereOvaGetParams() *V1OverlordsVsphereOvaGetParams {

	return &V1OverlordsVsphereOvaGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1OverlordsVsphereOvaGetParamsWithTimeout creates a new V1OverlordsVsphereOvaGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1OverlordsVsphereOvaGetParamsWithTimeout(timeout time.Duration) *V1OverlordsVsphereOvaGetParams {

	return &V1OverlordsVsphereOvaGetParams{

		timeout: timeout,
	}
}

// NewV1OverlordsVsphereOvaGetParamsWithContext creates a new V1OverlordsVsphereOvaGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1OverlordsVsphereOvaGetParamsWithContext(ctx context.Context) *V1OverlordsVsphereOvaGetParams {

	return &V1OverlordsVsphereOvaGetParams{

		Context: ctx,
	}
}

// NewV1OverlordsVsphereOvaGetParamsWithHTTPClient creates a new V1OverlordsVsphereOvaGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1OverlordsVsphereOvaGetParamsWithHTTPClient(client *http.Client) *V1OverlordsVsphereOvaGetParams {

	return &V1OverlordsVsphereOvaGetParams{
		HTTPClient: client,
	}
}

/*V1OverlordsVsphereOvaGetParams contains all the parameters to send to the API endpoint
for the v1 overlords vsphere ova get operation typically these are written to a http.Request
*/
type V1OverlordsVsphereOvaGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 overlords vsphere ova get params
func (o *V1OverlordsVsphereOvaGetParams) WithTimeout(timeout time.Duration) *V1OverlordsVsphereOvaGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 overlords vsphere ova get params
func (o *V1OverlordsVsphereOvaGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 overlords vsphere ova get params
func (o *V1OverlordsVsphereOvaGetParams) WithContext(ctx context.Context) *V1OverlordsVsphereOvaGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 overlords vsphere ova get params
func (o *V1OverlordsVsphereOvaGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 overlords vsphere ova get params
func (o *V1OverlordsVsphereOvaGetParams) WithHTTPClient(client *http.Client) *V1OverlordsVsphereOvaGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 overlords vsphere ova get params
func (o *V1OverlordsVsphereOvaGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1OverlordsVsphereOvaGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
