// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1ProjectsUIDValidateParams creates a new V1ProjectsUIDValidateParams object
// with the default values initialized.
func NewV1ProjectsUIDValidateParams() *V1ProjectsUIDValidateParams {
	var ()
	return &V1ProjectsUIDValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1ProjectsUIDValidateParamsWithTimeout creates a new V1ProjectsUIDValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1ProjectsUIDValidateParamsWithTimeout(timeout time.Duration) *V1ProjectsUIDValidateParams {
	var ()
	return &V1ProjectsUIDValidateParams{

		timeout: timeout,
	}
}

// NewV1ProjectsUIDValidateParamsWithContext creates a new V1ProjectsUIDValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1ProjectsUIDValidateParamsWithContext(ctx context.Context) *V1ProjectsUIDValidateParams {
	var ()
	return &V1ProjectsUIDValidateParams{

		Context: ctx,
	}
}

// NewV1ProjectsUIDValidateParamsWithHTTPClient creates a new V1ProjectsUIDValidateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1ProjectsUIDValidateParamsWithHTTPClient(client *http.Client) *V1ProjectsUIDValidateParams {
	var ()
	return &V1ProjectsUIDValidateParams{
		HTTPClient: client,
	}
}

/*V1ProjectsUIDValidateParams contains all the parameters to send to the API endpoint
for the v1 projects Uid validate operation typically these are written to a http.Request
*/
type V1ProjectsUIDValidateParams struct {

	/*UID*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) WithTimeout(timeout time.Duration) *V1ProjectsUIDValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) WithContext(ctx context.Context) *V1ProjectsUIDValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) WithHTTPClient(client *http.Client) *V1ProjectsUIDValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) WithUID(uid string) *V1ProjectsUIDValidateParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the v1 projects Uid validate params
func (o *V1ProjectsUIDValidateParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *V1ProjectsUIDValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
