// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1PasswordsBlockListUpdateParams creates a new V1PasswordsBlockListUpdateParams object
// with the default values initialized.
func NewV1PasswordsBlockListUpdateParams() *V1PasswordsBlockListUpdateParams {
	var ()
	return &V1PasswordsBlockListUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1PasswordsBlockListUpdateParamsWithTimeout creates a new V1PasswordsBlockListUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1PasswordsBlockListUpdateParamsWithTimeout(timeout time.Duration) *V1PasswordsBlockListUpdateParams {
	var ()
	return &V1PasswordsBlockListUpdateParams{

		timeout: timeout,
	}
}

// NewV1PasswordsBlockListUpdateParamsWithContext creates a new V1PasswordsBlockListUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1PasswordsBlockListUpdateParamsWithContext(ctx context.Context) *V1PasswordsBlockListUpdateParams {
	var ()
	return &V1PasswordsBlockListUpdateParams{

		Context: ctx,
	}
}

// NewV1PasswordsBlockListUpdateParamsWithHTTPClient creates a new V1PasswordsBlockListUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1PasswordsBlockListUpdateParamsWithHTTPClient(client *http.Client) *V1PasswordsBlockListUpdateParams {
	var ()
	return &V1PasswordsBlockListUpdateParams{
		HTTPClient: client,
	}
}

/*V1PasswordsBlockListUpdateParams contains all the parameters to send to the API endpoint
for the v1 passwords block list update operation typically these are written to a http.Request
*/
type V1PasswordsBlockListUpdateParams struct {

	/*Body*/
	Body *models.V1PasswordsBlockList

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) WithTimeout(timeout time.Duration) *V1PasswordsBlockListUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) WithContext(ctx context.Context) *V1PasswordsBlockListUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) WithHTTPClient(client *http.Client) *V1PasswordsBlockListUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) WithBody(body *models.V1PasswordsBlockList) *V1PasswordsBlockListUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 passwords block list update params
func (o *V1PasswordsBlockListUpdateParams) SetBody(body *models.V1PasswordsBlockList) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1PasswordsBlockListUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
