// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1SpectroClustersGkeValidateParams creates a new V1SpectroClustersGkeValidateParams object
// with the default values initialized.
func NewV1SpectroClustersGkeValidateParams() *V1SpectroClustersGkeValidateParams {
	var ()
	return &V1SpectroClustersGkeValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1SpectroClustersGkeValidateParamsWithTimeout creates a new V1SpectroClustersGkeValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1SpectroClustersGkeValidateParamsWithTimeout(timeout time.Duration) *V1SpectroClustersGkeValidateParams {
	var ()
	return &V1SpectroClustersGkeValidateParams{

		timeout: timeout,
	}
}

// NewV1SpectroClustersGkeValidateParamsWithContext creates a new V1SpectroClustersGkeValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1SpectroClustersGkeValidateParamsWithContext(ctx context.Context) *V1SpectroClustersGkeValidateParams {
	var ()
	return &V1SpectroClustersGkeValidateParams{

		Context: ctx,
	}
}

// NewV1SpectroClustersGkeValidateParamsWithHTTPClient creates a new V1SpectroClustersGkeValidateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1SpectroClustersGkeValidateParamsWithHTTPClient(client *http.Client) *V1SpectroClustersGkeValidateParams {
	var ()
	return &V1SpectroClustersGkeValidateParams{
		HTTPClient: client,
	}
}

/*V1SpectroClustersGkeValidateParams contains all the parameters to send to the API endpoint
for the v1 spectro clusters gke validate operation typically these are written to a http.Request
*/
type V1SpectroClustersGkeValidateParams struct {

	/*Body*/
	Body *models.V1SpectroGcpClusterEntity

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) WithTimeout(timeout time.Duration) *V1SpectroClustersGkeValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) WithContext(ctx context.Context) *V1SpectroClustersGkeValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) WithHTTPClient(client *http.Client) *V1SpectroClustersGkeValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) WithBody(body *models.V1SpectroGcpClusterEntity) *V1SpectroClustersGkeValidateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 spectro clusters gke validate params
func (o *V1SpectroClustersGkeValidateParams) SetBody(body *models.V1SpectroGcpClusterEntity) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1SpectroClustersGkeValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
