// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// V1TenantResourceLimitsGetReader is a Reader for the V1TenantResourceLimitsGet structure.
type V1TenantResourceLimitsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1TenantResourceLimitsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1TenantResourceLimitsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1TenantResourceLimitsGetOK creates a V1TenantResourceLimitsGetOK with default headers values
func NewV1TenantResourceLimitsGetOK() *V1TenantResourceLimitsGetOK {
	return &V1TenantResourceLimitsGetOK{}
}

/*V1TenantResourceLimitsGetOK handles this case with default header values.

(empty)
*/
type V1TenantResourceLimitsGetOK struct {
	Payload *models.V1TenantResourceLimits
}

func (o *V1TenantResourceLimitsGetOK) Error() string {
	return fmt.Sprintf("[GET /v1/tenants/{tenantUid}/resourceLimits][%d] v1TenantResourceLimitsGetOK  %+v", 200, o.Payload)
}

func (o *V1TenantResourceLimitsGetOK) GetPayload() *models.V1TenantResourceLimits {
	return o.Payload
}

func (o *V1TenantResourceLimitsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TenantResourceLimits)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
