// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// NewV1UsersAssetsLocationS3UpdateParams creates a new V1UsersAssetsLocationS3UpdateParams object
// with the default values initialized.
func NewV1UsersAssetsLocationS3UpdateParams() *V1UsersAssetsLocationS3UpdateParams {
	var ()
	return &V1UsersAssetsLocationS3UpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1UsersAssetsLocationS3UpdateParamsWithTimeout creates a new V1UsersAssetsLocationS3UpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1UsersAssetsLocationS3UpdateParamsWithTimeout(timeout time.Duration) *V1UsersAssetsLocationS3UpdateParams {
	var ()
	return &V1UsersAssetsLocationS3UpdateParams{

		timeout: timeout,
	}
}

// NewV1UsersAssetsLocationS3UpdateParamsWithContext creates a new V1UsersAssetsLocationS3UpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1UsersAssetsLocationS3UpdateParamsWithContext(ctx context.Context) *V1UsersAssetsLocationS3UpdateParams {
	var ()
	return &V1UsersAssetsLocationS3UpdateParams{

		Context: ctx,
	}
}

// NewV1UsersAssetsLocationS3UpdateParamsWithHTTPClient creates a new V1UsersAssetsLocationS3UpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1UsersAssetsLocationS3UpdateParamsWithHTTPClient(client *http.Client) *V1UsersAssetsLocationS3UpdateParams {
	var ()
	return &V1UsersAssetsLocationS3UpdateParams{
		HTTPClient: client,
	}
}

/*
V1UsersAssetsLocationS3UpdateParams contains all the parameters to send to the API endpoint
for the v1 users assets location s3 update operation typically these are written to a http.Request
*/
type V1UsersAssetsLocationS3UpdateParams struct {

	/*Body*/
	Body *models.V1UserAssetsLocationS3
	/*UID
	  Specify the S3 location uid

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) WithTimeout(timeout time.Duration) *V1UsersAssetsLocationS3UpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) WithContext(ctx context.Context) *V1UsersAssetsLocationS3UpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) WithHTTPClient(client *http.Client) *V1UsersAssetsLocationS3UpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) WithBody(body *models.V1UserAssetsLocationS3) *V1UsersAssetsLocationS3UpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) SetBody(body *models.V1UserAssetsLocationS3) {
	o.Body = body
}

// WithUID adds the uid to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) WithUID(uid string) *V1UsersAssetsLocationS3UpdateParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the v1 users assets location s3 update params
func (o *V1UsersAssetsLocationS3UpdateParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *V1UsersAssetsLocationS3UpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
