// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spectrocloud/palette-sdk-go/api/models"
)

// V1VsphereDNSMappingsGetReader is a Reader for the V1VsphereDNSMappingsGet structure.
type V1VsphereDNSMappingsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1VsphereDNSMappingsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1VsphereDNSMappingsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1VsphereDNSMappingsGetOK creates a V1VsphereDNSMappingsGetOK with default headers values
func NewV1VsphereDNSMappingsGetOK() *V1VsphereDNSMappingsGetOK {
	return &V1VsphereDNSMappingsGetOK{}
}

/*
V1VsphereDNSMappingsGetOK handles this case with default header values.

(empty)
*/
type V1VsphereDNSMappingsGetOK struct {
	Payload *models.V1VsphereDNSMappings
}

func (o *V1VsphereDNSMappingsGetOK) Error() string {
	return fmt.Sprintf("[GET /v1/users/assets/vsphere/dnsMappings][%d] v1VsphereDnsMappingsGetOK  %+v", 200, o.Payload)
}

func (o *V1VsphereDNSMappingsGetOK) GetPayload() *models.V1VsphereDNSMappings {
	return o.Payload
}

func (o *V1VsphereDNSMappingsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1VsphereDNSMappings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
