name: GoLicensesPRValidation
on: [pull_request]

concurrency:
  group: go-licenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-licenses-pr-scan:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/spectro-images-public/golang:1.22-alpine
    steps:
      - name: install-go-licenses
        run: GOBIN=/usr/local/bin go install github.com/google/go-licenses@latest

      - name: checkout
        uses: actions/checkout@v3

      - name: set-github-access
        run: |
          /usr/bin/git config --global --add url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github".insteadOf https://github
          /usr/bin/git config --global --add url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github".insteadOf git@github

      - name: go-licenses-scan
        run: go-licenses check --ignore github.com/spectrocloud --ignore github.com/spectrocloud/palette-api-go ./...